#!/bin/bash
# This file should be sourced
# alias mkcd=". mkcd"

if [ ! -z "$1" ]
then
		mkdir $1
		cd $1
else
		echo "mkcd: missing operand"
		echo "usage: mkcd [foldername]
		Create and change directory."
fi		